### PR TITLE
Simplify code and check valid pages

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by gfischershaw** [comment]
Thanks. Yes, the duplicate code bugged me, but I was not sure if someone would complain if I changed too much. And obviously I do not know enough yet with regards to various error returns. One minor typo should be fixed in the for() loop statement on the resulting line 130.

**Comment by mlocati** [comment]
> One minor typo should be fixed in the for() loop statement on the resulting line 130.

Which typo?

**Comment by gfischershaw** [comment]
Sorry. Just move the conditionals into the middle.

**Comment by mlocati** [comment]
Whoops, you are right

**Comment by mlocati** [comment]
PR updated, thanks

**Comment by mlocati** [comment]
> I was not sure if someone would complain if I changed too much.

If code becomes simpler, nobody will complain :wink:

**Pull request merged**
